export const INITIAL_CLUBS = [
  {
    id: "club-1",
    name: "Dhaka Dominators Esports",
    shortName: "DDE",
    slug: "dhaka-dominators",
    logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-1",
    managerName: "Rahim Chowdhury",
    location: "Dhaka, Bangladesh",
    facebookPage: "https://facebook.com/dhakadominators",
    description: "Reigning eFCOB Premier Division Champions. Known for high-intensity Gegenpressing and clinical wing play.",
    foundedDate: "2023-01-15T00:00:00Z",
    status: "ACTIVE",
    marketValue: 480.5,
    points: 38,
    formHistory: "W,W,W,D,W",
    trophiesCount: 4,
    stats: { matches: 16, wins: 12, draws: 2, losses: 2, winRate: 75.0, goalsScored: 42, goalsConceded: 14 }
  },
  {
    id: "club-2",
    name: "Chittagong Cyber Kings",
    shortName: "CCK",
    slug: "chittagong-cyber-kings",
    logo: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-2",
    managerName: "Nafis Arman",
    location: "Chittagong, Bangladesh",
    facebookPage: "https://facebook.com/chittagongcyberkings",
    description: "Port City powerhouse with explosive counter-attacking football and disciplined tactical structure.",
    foundedDate: "2023-03-10T00:00:00Z",
    status: "ACTIVE",
    marketValue: 420.0,
    points: 35,
    formHistory: "W,W,D,W,L",
    trophiesCount: 3,
    stats: { matches: 16, wins: 11, draws: 2, losses: 3, winRate: 68.8, goalsScored: 36, goalsConceded: 16 }
  },
  {
    id: "club-3",
    name: "Sylhet Strikers Esports",
    shortName: "SSE",
    slug: "sylhet-strikers",
    logo: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-3",
    managerName: "Faysal Ahmed",
    location: "Sylhet, Bangladesh",
    facebookPage: "https://facebook.com/sylhetstrikers",
    description: "Tea City warriors celebrated for creative possession-based build up and solid defensive anchors.",
    foundedDate: "2023-05-20T00:00:00Z",
    status: "ACTIVE",
    marketValue: 395.0,
    points: 31,
    formHistory: "D,W,W,W,L",
    trophiesCount: 2,
    stats: { matches: 16, wins: 9, draws: 4, losses: 3, winRate: 56.3, goalsScored: 31, goalsConceded: 18 }
  },
  {
    id: "club-4",
    name: "Rajshahi Royal FC",
    shortName: "RRF",
    slug: "rajshahi-royal",
    logo: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-4",
    managerName: "Mahbubur Rahman",
    location: "Rajshahi, Bangladesh",
    facebookPage: "https://facebook.com/rajshahiroyal",
    description: "Silk City Titans with rapid vertical transition play and world-class set piece execution.",
    foundedDate: "2023-08-01T00:00:00Z",
    status: "ACTIVE",
    marketValue: 360.0,
    points: 29,
    formHistory: "W,L,W,D,W",
    trophiesCount: 2,
    stats: { matches: 16, wins: 9, draws: 2, losses: 5, winRate: 56.3, goalsScored: 28, goalsConceded: 20 }
  },
  {
    id: "club-5",
    name: "Barisal Blasters",
    shortName: "BBL",
    slug: "barisal-blasters",
    logo: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-5",
    managerName: "Al-Amin Hossain",
    location: "Barisal, Bangladesh",
    facebookPage: "https://facebook.com/barisalblasters",
    description: "Southern predators known for fearless underdog triumphs and high pressing midfield lines.",
    foundedDate: "2023-11-12T00:00:00Z",
    status: "ACTIVE",
    marketValue: 310.0,
    points: 25,
    formHistory: "L,W,D,W,L",
    trophiesCount: 1,
    stats: { matches: 16, wins: 7, draws: 4, losses: 5, winRate: 43.8, goalsScored: 24, goalsConceded: 22 }
  },
  {
    id: "club-6",
    name: "Khulna Knights Esports",
    shortName: "KKE",
    slug: "khulna-knights",
    logo: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-6",
    managerName: "Tariqul Islam",
    location: "Khulna, Bangladesh",
    facebookPage: "https://facebook.com/khulnaknights",
    description: "Sundarbans warriors boasting ironclad defensive records and ruthless counter attacking.",
    foundedDate: "2024-01-05T00:00:00Z",
    status: "ACTIVE",
    marketValue: 290.0,
    points: 22,
    formHistory: "W,L,L,W,D",
    trophiesCount: 1,
    stats: { matches: 16, wins: 6, draws: 4, losses: 6, winRate: 37.5, goalsScored: 20, goalsConceded: 21 }
  },
  {
    id: "club-7",
    name: "Rangpur Riders Esports",
    shortName: "RRE",
    slug: "rangpur-riders",
    logo: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-7",
    managerName: "Shafiqul Alam",
    location: "Rangpur, Bangladesh",
    facebookPage: "https://facebook.com/rangpurriders",
    description: "Northern pride featuring young prodigies and innovative possession strategies.",
    foundedDate: "2024-02-14T00:00:00Z",
    status: "ACTIVE",
    marketValue: 275.0,
    points: 19,
    formHistory: "L,D,W,L,W",
    trophiesCount: 0,
    stats: { matches: 16, wins: 5, draws: 4, losses: 7, winRate: 31.3, goalsScored: 19, goalsConceded: 26 }
  },
  {
    id: "club-8",
    name: "Comilla Conquerors",
    shortName: "CCQ",
    slug: "comilla-conquerors",
    logo: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-8",
    managerName: "Arifur Zaman",
    location: "Comilla, Bangladesh",
    facebookPage: "https://facebook.com/comillaconquerors",
    description: "Historic battlers with tenacious high line defending and quick through-ball finishes.",
    foundedDate: "2024-03-01T00:00:00Z",
    status: "ACTIVE",
    marketValue: 240.0,
    points: 16,
    formHistory: "L,L,D,W,L",
    trophiesCount: 0,
    stats: { matches: 16, wins: 4, draws: 4, losses: 8, winRate: 25.0, goalsScored: 17, goalsConceded: 29 }
  },
  {
    id: "club-9",
    name: "Bogra Ballers Esports",
    shortName: "BBE",
    slug: "bogra-ballers",
    logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-9",
    managerName: "Zahid Hasan",
    location: "Bogra, Bangladesh",
    facebookPage: "https://facebook.com/bograballers",
    description: "Pundranagar powerhouse hungry for glory with electric frontline dynamism.",
    foundedDate: "2024-04-10T00:00:00Z",
    status: "ACTIVE",
    marketValue: 215.0,
    points: 13,
    formHistory: "L,L,L,D,W",
    trophiesCount: 0,
    stats: { matches: 16, wins: 3, draws: 4, losses: 9, winRate: 18.8, goalsScored: 14, goalsConceded: 32 }
  },
  {
    id: "club-10",
    name: "Mymensingh Mavericks",
    shortName: "MMV",
    slug: "mymensingh-mavericks",
    logo: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80",
    managerId: "user-mgr-10",
    managerName: "Tanvir Anjum",
    location: "Mymensingh, Bangladesh",
    facebookPage: "https://facebook.com/mymensinghmavericks",
    description: "Brahmaputra stars bringing raw agility, fast dribbling and disciplined zonal marking.",
    foundedDate: "2024-05-01T00:00:00Z",
    status: "ACTIVE",
    marketValue: 190.0,
    points: 10,
    formHistory: "L,L,D,L,L",
    trophiesCount: 0,
    stats: { matches: 16, wins: 2, draws: 4, losses: 10, winRate: 12.5, goalsScored: 12, goalsConceded: 35 }
  }
];

// 50 Detailed Realistic Players
export const INITIAL_PLAYERS = [
  {
    id: "player-1",
    userId: "user-p-1",
    username: "mahim_striker",
    fullName: "Mahim Haider",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    konamiId: "984-721-032",
    deviceModel: "iPhone 15 Pro Max",
    preferredPosition: "CF",
    playStyle: "Quick Counter",
    bio: "eFCOB Golden Boot Winner 2025. Lethal finisher in the box with 90+ finishing & offensive awareness.",
    rating: 965,
    marketValue: 220.0,
    status: "ACTIVE",
    formHistory: "W,W,W,W,W",
    motmCount: 14,
    clubId: "club-1",
    stats: { matchesPlayed: 48, wins: 39, draws: 5, losses: 4, winRate: 81.3, goalsScored: 64, assists: 19, cleanSheets: 0, points: 122 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 18, daysRemaining: 340 }
  },
  {
    id: "player-2",
    userId: "user-p-2",
    username: "prasen_legend",
    fullName: "Prasen Jit Sarker",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    konamiId: "812-493-219",
    deviceModel: "Samsung Galaxy S24 Ultra",
    preferredPosition: "AMF",
    playStyle: "Possession Game",
    bio: "Master playmaker with pinpoint through passes, double touch mastery, and long range stunner goals.",
    rating: 950,
    marketValue: 205.0,
    status: "ACTIVE",
    formHistory: "W,W,W,D,W",
    motmCount: 12,
    clubId: "club-2",
    stats: { matchesPlayed: 45, wins: 36, draws: 6, losses: 3, winRate: 80.0, goalsScored: 38, assists: 32, cleanSheets: 0, points: 114 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 12, daysRemaining: 215 }
  },
  {
    id: "player-3",
    userId: "user-p-3",
    username: "tanvir_efootball",
    fullName: "Tanvir Ahmed Chowdhury",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    konamiId: "472-839-102",
    deviceModel: "iPad Pro M2",
    preferredPosition: "SS",
    playStyle: "Out Wide",
    bio: "Tricky shadow striker known for curl shots, tight possession dribbling and clutch tournament finishes.",
    rating: 935,
    marketValue: 185.0,
    status: "ACTIVE",
    formHistory: "W,D,W,W,W",
    motmCount: 10,
    clubId: "club-1",
    stats: { matchesPlayed: 42, wins: 32, draws: 6, losses: 4, winRate: 76.2, goalsScored: 41, assists: 22, cleanSheets: 0, points: 102 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 24, daysRemaining: 510 }
  },
  {
    id: "player-4",
    userId: "user-p-4",
    username: "shakib_tactician",
    fullName: "Shakib Al Hasan",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80",
    konamiId: "309-182-745",
    deviceModel: "iPhone 14 Pro",
    preferredPosition: "DMF",
    playStyle: "Long Ball Counter",
    bio: "Unbreakable defensive anchor. Leads the league in interceptions, tackle success rate and counter setup.",
    rating: 920,
    marketValue: 165.0,
    status: "ACTIVE",
    formHistory: "W,W,D,W,L",
    motmCount: 8,
    clubId: "club-3",
    stats: { matchesPlayed: 44, wins: 31, draws: 7, losses: 6, winRate: 70.5, goalsScored: 12, assists: 24, cleanSheets: 18, points: 100 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 12, daysRemaining: 180 }
  },
  {
    id: "player-5",
    userId: "user-p-5",
    username: "easin_pro",
    fullName: "Easin Arafat",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80",
    konamiId: "198-472-381",
    deviceModel: "ROG Phone 8 Pro",
    preferredPosition: "RWF",
    playStyle: "Quick Counter",
    bio: "Lightning fast speedster on the right wing. Specialized in sharp cut-ins and blitzing long range curls.",
    rating: 915,
    marketValue: 155.0,
    status: "ACTIVE",
    formHistory: "W,W,W,L,W",
    motmCount: 9,
    clubId: "club-4",
    stats: { matchesPlayed: 40, wins: 28, draws: 6, losses: 6, winRate: 70.0, goalsScored: 34, assists: 20, cleanSheets: 0, points: 90 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 12, daysRemaining: 195 }
  },
  {
    id: "player-6",
    userId: "user-p-6",
    username: "fahim_finisher",
    fullName: "Fahim Shahriar",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80",
    konamiId: "561-294-817",
    deviceModel: "OnePlus 12",
    preferredPosition: "CF",
    playStyle: "Possession Game",
    bio: "Clinical poacher with supreme header accuracy and devastating near-post first-time shots.",
    rating: 895,
    marketValue: 135.0,
    status: "ACTIVE",
    formHistory: "D,W,W,L,W",
    motmCount: 7,
    clubId: "club-2",
    stats: { matchesPlayed: 38, wins: 25, draws: 7, losses: 6, winRate: 65.8, goalsScored: 29, assists: 14, cleanSheets: 0, points: 82 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 6, daysRemaining: 86 }
  },
  {
    id: "player-7",
    userId: "user-p-7",
    username: "rakib_maestro",
    fullName: "Rakibul Islam",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80",
    konamiId: "729-104-582",
    deviceModel: "POCO F5",
    preferredPosition: "CMF",
    playStyle: "Possession Game",
    bio: "Box-to-box midfielder with stamina and high defensive awareness.",
    rating: 885,
    marketValue: 120.0,
    status: "ACTIVE",
    formHistory: "W,L,W,W,D",
    motmCount: 6,
    clubId: "club-3",
    stats: { matchesPlayed: 36, wins: 22, draws: 8, losses: 6, winRate: 61.1, goalsScored: 15, assists: 21, cleanSheets: 8, points: 74 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 12, daysRemaining: 240 }
  },
  {
    id: "player-8",
    userId: "user-p-8",
    username: "arif_thewall",
    fullName: "Arifuzzaman Khan",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    konamiId: "648-912-305",
    deviceModel: "iPhone 15 Pro",
    preferredPosition: "CB",
    playStyle: "Long Ball Counter",
    bio: "Impassable central defender. Known as 'The Wall of Dhaka' for dominant aerial duels and goal-line stops.",
    rating: 880,
    marketValue: 115.0,
    status: "ACTIVE",
    formHistory: "W,W,L,W,D",
    motmCount: 5,
    clubId: "club-1",
    stats: { matchesPlayed: 38, wins: 24, draws: 7, losses: 7, winRate: 63.2, goalsScored: 4, assists: 6, cleanSheets: 19, points: 79 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 18, daysRemaining: 390 }
  },
  {
    id: "player-9",
    userId: "user-p-9",
    username: "sabbir_dribbler",
    fullName: "Sabbir Hossain",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80",
    konamiId: "284-950-163",
    deviceModel: "iPad Air M1",
    preferredPosition: "LWF",
    playStyle: "Quick Counter",
    bio: "Sensational dribbling technician on the left flank with elite skill cancels.",
    rating: 870,
    marketValue: 105.0,
    status: "ACTIVE",
    formHistory: "L,W,W,D,W",
    motmCount: 5,
    clubId: "club-5",
    stats: { matchesPlayed: 34, wins: 20, draws: 6, losses: 8, winRate: 58.8, goalsScored: 24, assists: 15, cleanSheets: 0, points: 66 },
    contract: { status: "TRANSFER_LISTED", durationMonths: 4, daysRemaining: 45 }
  },
  {
    id: "player-10",
    userId: "user-p-10",
    username: "jubayer_gk",
    fullName: "Jubayer Mahmud",
    avatar: "https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=300&auto=format&fit=crop&q=80",
    konamiId: "401-729-883",
    deviceModel: "Samsung Galaxy S23",
    preferredPosition: "GK",
    playStyle: "Possession Game",
    bio: "Top goalkeeper in the circuit with reflexive penalty saves and rapid sweeper keeper clearances.",
    rating: 865,
    marketValue: 98.0,
    status: "ACTIVE",
    formHistory: "W,D,L,W,W",
    motmCount: 4,
    clubId: "club-2",
    stats: { matchesPlayed: 35, wins: 21, draws: 7, losses: 7, winRate: 60.0, goalsScored: 0, assists: 2, cleanSheets: 16, points: 70 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 12, daysRemaining: 210 }
  },
  // Players 11 - 25
  {
    id: "player-11",
    userId: "user-p-11",
    username: "mustafiz_speed",
    fullName: "Mustafizur Rahman",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    konamiId: "119-482-901",
    deviceModel: "Xiaomi 14 Ultra",
    preferredPosition: "RB",
    playStyle: "Out Wide",
    bio: "High stamina fullback with pinpoint crossing and aggressive overlap runs.",
    rating: 855,
    marketValue: 88.0,
    status: "ACTIVE",
    formHistory: "W,L,W,D,L",
    motmCount: 3,
    clubId: "club-4",
    stats: { matchesPlayed: 32, wins: 18, draws: 6, losses: 8, winRate: 56.3, goalsScored: 3, assists: 14, cleanSheets: 12, points: 60 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 8, daysRemaining: 120 }
  },
  {
    id: "player-12",
    userId: "user-p-12",
    username: "shanto_wizard",
    fullName: "Najmul Hossain Shanto",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    konamiId: "938-201-445",
    deviceModel: "Realme GT Neo 5",
    preferredPosition: "AMF",
    playStyle: "Possession Game",
    bio: "Agile attacking midfielder with quick turns and stunning curlers from outside the box.",
    rating: 850,
    marketValue: 82.0,
    status: "ACTIVE",
    formHistory: "L,W,W,L,D",
    motmCount: 4,
    clubId: "club-6",
    stats: { matchesPlayed: 30, wins: 15, draws: 7, losses: 8, winRate: 50.0, goalsScored: 18, assists: 16, cleanSheets: 0, points: 52 },
    contract: { status: "FREE_AGENT", durationMonths: 0, daysRemaining: 0 }
  },
  {
    id: "player-13",
    userId: "user-p-13",
    username: "taslim_sniper",
    fullName: "Taslim Ahmed",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80",
    konamiId: "384-910-276",
    deviceModel: "iPhone 13 Pro",
    preferredPosition: "CF",
    playStyle: "Quick Counter",
    bio: "Sharp shooter specializing in first-touch dipping knuckle balls.",
    rating: 845,
    marketValue: 78.0,
    status: "ACTIVE",
    formHistory: "W,W,L,D,L",
    motmCount: 3,
    clubId: "club-5",
    stats: { matchesPlayed: 28, wins: 14, draws: 6, losses: 8, winRate: 50.0, goalsScored: 21, assists: 7, cleanSheets: 0, points: 48 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 10, daysRemaining: 150 }
  },
  {
    id: "player-14",
    userId: "user-p-14",
    username: "hasan_shield",
    fullName: "Hasan Ali",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    konamiId: "602-184-927",
    deviceModel: "POCO F5",
    preferredPosition: "LB",
    playStyle: "Long Ball Counter",
    bio: "Tenacious left back with exceptional sliding tackles and defensive positioning.",
    rating: 835,
    marketValue: 70.0,
    status: "ACTIVE",
    formHistory: "D,L,W,W,L",
    motmCount: 2,
    clubId: "club-6",
    stats: { matchesPlayed: 27, wins: 13, draws: 6, losses: 8, winRate: 48.1, goalsScored: 2, assists: 9, cleanSheets: 10, points: 45 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 12, daysRemaining: 270 }
  },
  {
    id: "player-15",
    userId: "user-p-15",
    username: "maruf_rising",
    fullName: "Maruf Hossain",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80",
    konamiId: "759-301-840",
    deviceModel: "iPhone 14",
    preferredPosition: "RWF",
    playStyle: "Out Wide",
    bio: "Rising Star of the season. 18-year-old talent making waves with blistering pace.",
    rating: 830,
    marketValue: 68.0,
    status: "ACTIVE",
    formHistory: "W,W,W,L,W",
    motmCount: 4,
    clubId: "club-7",
    stats: { matchesPlayed: 25, wins: 14, draws: 4, losses: 7, winRate: 56.0, goalsScored: 16, assists: 11, cleanSheets: 0, points: 46 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 24, daysRemaining: 600 }
  },
  {
    id: "player-16",
    userId: "user-p-16",
    username: "joy_passmaster",
    fullName: "Mahmudul Hasan Joy",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80",
    konamiId: "492-018-375",
    deviceModel: "Samsung Galaxy S22 Ultra",
    preferredPosition: "CMF",
    playStyle: "Possession Game",
    bio: "Metronome of the midfield with 92% pass completion in division 1 matches.",
    rating: 825,
    marketValue: 62.0,
    status: "ACTIVE",
    formHistory: "L,D,W,L,W",
    motmCount: 2,
    clubId: "club-7",
    stats: { matchesPlayed: 26, wins: 12, draws: 6, losses: 8, winRate: 46.2, goalsScored: 7, assists: 15, cleanSheets: 5, points: 42 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 6, daysRemaining: 75 }
  },
  {
    id: "player-17",
    userId: "user-p-17",
    username: "badhon_bullet",
    fullName: "Badhon Roy",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    konamiId: "810-394-521",
    deviceModel: "OnePlus 11",
    preferredPosition: "CF",
    playStyle: "Quick Counter",
    bio: "Direct counter attacker with blazing sprint acceleration.",
    rating: 815,
    marketValue: 56.0,
    status: "ACTIVE",
    formHistory: "L,L,W,D,L",
    motmCount: 2,
    clubId: "club-8",
    stats: { matchesPlayed: 24, wins: 10, draws: 5, losses: 9, winRate: 41.7, goalsScored: 14, assists: 5, cleanSheets: 0, points: 35 },
    contract: { status: "TRANSFER_LISTED", durationMonths: 3, daysRemaining: 30 }
  },
  {
    id: "player-18",
    userId: "user-p-18",
    username: "shafi_iron",
    fullName: "Shafiul Islam",
    avatar: "https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=300&auto=format&fit=crop&q=80",
    konamiId: "374-829-105",
    deviceModel: "ROG Phone 7",
    preferredPosition: "CB",
    playStyle: "Long Ball Counter",
    bio: "Rugged center back with physical dominance in 1v1 situations.",
    rating: 810,
    marketValue: 52.0,
    status: "ACTIVE",
    formHistory: "L,W,L,D,L",
    motmCount: 1,
    clubId: "club-8",
    stats: { matchesPlayed: 25, wins: 9, draws: 6, losses: 10, winRate: 36.0, goalsScored: 1, assists: 3, cleanSheets: 7, points: 33 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 12, daysRemaining: 220 }
  },
  {
    id: "player-19",
    userId: "user-p-19",
    username: "tamim_flank",
    fullName: "Tamim Iqbal Jr",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    konamiId: "650-192-834",
    deviceModel: "iPhone 15",
    preferredPosition: "LWF",
    playStyle: "Out Wide",
    bio: "Explosive left winger with signature step-overs and rabona crosses.",
    rating: 800,
    marketValue: 48.0,
    status: "ACTIVE",
    formHistory: "L,L,D,W,L",
    motmCount: 1,
    clubId: "club-9",
    stats: { matchesPlayed: 22, wins: 8, draws: 4, losses: 10, winRate: 36.4, goalsScored: 11, assists: 7, cleanSheets: 0, points: 28 },
    contract: { status: "FREE_AGENT", durationMonths: 0, daysRemaining: 0 }
  },
  {
    id: "player-20",
    userId: "user-p-20",
    username: "ripon_hands",
    fullName: "Ripon Mondol",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    konamiId: "921-483-019",
    deviceModel: "Xiaomi 13 Pro",
    preferredPosition: "GK",
    playStyle: "Possession Game",
    bio: "Calm and composed shot stopper with quick distribution.",
    rating: 795,
    marketValue: 42.0,
    status: "ACTIVE",
    formHistory: "L,L,L,D,W",
    motmCount: 1,
    clubId: "club-9",
    stats: { matchesPlayed: 22, wins: 7, draws: 5, losses: 10, winRate: 31.8, goalsScored: 0, assists: 1, cleanSheets: 6, points: 26 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 12, daysRemaining: 310 }
  },
  {
    id: "player-21",
    userId: "user-p-21",
    username: "sujon_dynamo",
    fullName: "Sujon Mia",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80",
    konamiId: "183-920-475",
    deviceModel: "Realme GT 2",
    preferredPosition: "DMF",
    playStyle: "Possession Game",
    bio: "Hard working midfield retriever.",
    rating: 785,
    marketValue: 36.0,
    status: "ACTIVE",
    formHistory: "L,L,D,L,L",
    motmCount: 0,
    clubId: "club-10",
    stats: { matchesPlayed: 20, wins: 5, draws: 5, losses: 10, winRate: 25.0, goalsScored: 3, assists: 6, cleanSheets: 3, points: 20 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 12, daysRemaining: 180 }
  },
  {
    id: "player-22",
    userId: "user-p-22",
    username: "alvi_fox",
    fullName: "Alvi Hasan",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    konamiId: "572-839-104",
    deviceModel: "iPhone 13",
    preferredPosition: "CF",
    playStyle: "Quick Counter",
    bio: "Fox in the box with uncanny penalty box instincts.",
    rating: 780,
    marketValue: 34.0,
    status: "ACTIVE",
    formHistory: "L,L,L,D,L",
    motmCount: 1,
    clubId: "club-10",
    stats: { matchesPlayed: 19, wins: 4, draws: 4, losses: 11, winRate: 21.1, goalsScored: 9, assists: 3, cleanSheets: 0, points: 16 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 8, daysRemaining: 110 }
  },
  {
    id: "player-23",
    userId: "user-p-23",
    username: "anowar_lock",
    fullName: "Anowar Hossain",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80",
    konamiId: "840-192-385",
    deviceModel: "Samsung A54",
    preferredPosition: "CB",
    playStyle: "Long Ball Counter",
    bio: "Aggressive center back with physical tackles.",
    rating: 770,
    marketValue: 28.0,
    status: "SUSPENDED",
    formHistory: "L,L,L,L,D",
    motmCount: 0,
    clubId: "club-10",
    stats: { matchesPlayed: 18, wins: 3, draws: 4, losses: 11, winRate: 16.7, goalsScored: 1, assists: 1, cleanSheets: 2, points: 13 },
    contract: { status: "UNDER_CONTRACT", durationMonths: 6, daysRemaining: 90 }
  },
  {
    id: "player-24",
    userId: "user-p-24",
    username: "shuvo_free",
    fullName: "Shuvashis Roy",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80",
    konamiId: "302-849-176",
    deviceModel: "POCO X5 Pro",
    preferredPosition: "AMF",
    playStyle: "Possession Game",
    bio: "Unattached creative midfielder looking for an ambitious club.",
    rating: 790,
    marketValue: 38.0,
    status: "ACTIVE",
    formHistory: "W,D,L,W,D",
    motmCount: 2,
    clubId: undefined,
    stats: { matchesPlayed: 20, wins: 9, draws: 4, losses: 7, winRate: 45.0, goalsScored: 11, assists: 10, cleanSheets: 0, points: 31 },
    contract: { status: "FREE_AGENT", durationMonths: 0, daysRemaining: 0 }
  },
  {
    id: "player-25",
    userId: "user-p-25",
    username: "bappi_free",
    fullName: "Bappi Kumar",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    konamiId: "719-382-904",
    deviceModel: "iPhone 12 Pro",
    preferredPosition: "RWF",
    playStyle: "Quick Counter",
    bio: "Free agent winger with high crossing accuracy.",
    rating: 775,
    marketValue: 30.0,
    status: "ACTIVE",
    formHistory: "D,W,L,L,W",
    motmCount: 1,
    clubId: undefined,
    stats: { matchesPlayed: 18, wins: 7, draws: 4, losses: 7, winRate: 38.9, goalsScored: 8, assists: 8, cleanSheets: 0, points: 25 },
    contract: { status: "FREE_AGENT", durationMonths: 0, daysRemaining: 0 }
  }
];

export const INITIAL_REFEREES = [
  {
    id: "ref-1",
    userId: "user-ref-1",
    officialId: "REF-BD-001",
    name: "Tanzid Hasan Joy",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    tier: "TIER_1",
    rating: 4.95,
    matchesOfficiated: 124,
    completedMatches: 122,
    disputesHandled: 18,
    status: "ACTIVE",
    joinedDate: "2023-01-10T00:00:00Z",
    role: "Senior Head Official"
  },
  {
    id: "ref-2",
    userId: "user-ref-2",
    officialId: "REF-BD-002",
    name: "Kamrul Islam Rabbi",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    tier: "TIER_1",
    rating: 4.90,
    matchesOfficiated: 98,
    completedMatches: 96,
    disputesHandled: 12,
    status: "ACTIVE",
    joinedDate: "2023-04-15T00:00:00Z",
    role: "National Tournament Referee"
  },
  {
    id: "ref-3",
    userId: "user-ref-3",
    officialId: "REF-BD-003",
    name: "Shamim Hossain Patwary",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80",
    tier: "TIER_2",
    rating: 4.82,
    matchesOfficiated: 65,
    completedMatches: 64,
    disputesHandled: 8,
    status: "ACTIVE",
    joinedDate: "2023-09-20T00:00:00Z",
    role: "League Official"
  },
  {
    id: "ref-4",
    userId: "user-ref-4",
    officialId: "REF-BD-004",
    name: "Mehedi Hasan Rana",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80",
    tier: "TIER_2",
    rating: 4.75,
    matchesOfficiated: 52,
    completedMatches: 50,
    disputesHandled: 6,
    status: "ACTIVE",
    joinedDate: "2024-01-10T00:00:00Z",
    role: "League Official"
  },
  {
    id: "ref-5",
    userId: "user-ref-5",
    officialId: "REF-BD-005",
    name: "Ziaur Rahman",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    tier: "TIER_3",
    rating: 4.60,
    matchesOfficiated: 34,
    completedMatches: 33,
    disputesHandled: 4,
    status: "ACTIVE",
    joinedDate: "2024-03-01T00:00:00Z",
    role: "Junior Match Adjudicator"
  },
  {
    id: "ref-6",
    userId: "user-ref-6",
    officialId: "REF-BD-006",
    name: "Nayeem Hasan",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80",
    tier: "TIER_3",
    rating: 4.55,
    matchesOfficiated: 28,
    completedMatches: 28,
    disputesHandled: 2,
    status: "ACTIVE",
    joinedDate: "2024-05-15T00:00:00Z",
    role: "Junior Match Adjudicator"
  }
];

export const INITIAL_TOURNAMENTS = [
  {
    id: "tourn-1",
    name: "Bangladesh National eFootball Championship 2026",
    slug: "national-championship-2026",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80",
    logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80",
    description: "The flagship tournament of Bangladesh eFootball featuring 32 elite players competing in a double elimination knockout bracket for the coveted National Championship Trophy and 100,000 BDT prize pool.",
    format: "SINGLE_ELIMINATION",
    gameCategory: "eFootball Mobile",
    platform: "Mobile",
    startDate: "2026-09-10T14:00:00Z",
    endDate: "2026-09-28T20:00:00Z",
    registrationDeadline: "2026-09-08T23:59:59Z",
    maxParticipants: 32,
    currentParticipants: 32,
    prizePool: "100,000 BDT",
    status: "ONGOING",
    progressPercent: 75,
    completedMatches: 24,
    totalMatches: 31
  },
  {
    id: "tourn-2",
    name: "eFCOB Premier Super League — Season 4",
    slug: "premier-super-league-s4",
    banner: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80",
    logo: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=200&auto=format&fit=crop&q=80",
    description: "Official 10-club round-robin league. Home & Away fixtures with full statistics tracking, weekly highlights, and broadcast on official stream channels.",
    format: "LEAGUE_ROUND_ROBIN",
    gameCategory: "eFootball Mobile",
    platform: "Mobile",
    startDate: "2026-08-01T15:00:00Z",
    endDate: "2026-10-15T22:00:00Z",
    registrationDeadline: "2026-07-25T23:59:59Z",
    maxParticipants: 10,
    currentParticipants: 10,
    prizePool: "150,000 BDT",
    status: "ONGOING",
    progressPercent: 62,
    completedMatches: 56,
    totalMatches: 90
  },
  {
    id: "tourn-3",
    name: "Dhaka Esports Champions Cup 2026",
    slug: "dhaka-champions-cup-2026",
    banner: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=1200&auto=format&fit=crop&q=80",
    logo: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=200&auto=format&fit=crop&q=80",
    description: "Open community tournament for all registered clubs and emerging grassroots players across the nation.",
    format: "GROUP_AND_KNOCKOUT",
    gameCategory: "eFootball Mobile",
    platform: "Mobile",
    startDate: "2026-10-01T12:00:00Z",
    endDate: "2026-10-20T21:00:00Z",
    registrationDeadline: "2026-09-27T23:59:59Z",
    maxParticipants: 16,
    currentParticipants: 12,
    prizePool: "50,000 BDT",
    status: "REGISTRATION_OPEN",
    progressPercent: 0,
    completedMatches: 0,
    totalMatches: 32
  }
];

export const INITIAL_FIXTURES = [
  // Live Matches
  {
    id: "fix-live-1",
    tournamentId: "tourn-1",
    tournamentName: "National Championship 2026",
    round: "Semi Final 1",
    scheduledDate: "2026-09-19T18:30:00Z",
    venue: "Server BD-Championship-01",
    status: "LIVE",
    isOnStream: true,
    streamPlatform: "YouTube",
    streamUrl: "https://www.youtube.com/watch?v=live_demo",
    homePlayer: { id: "player-1", username: "mahim_striker", fullName: "Mahim Haider", rating: 965, avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80" },
    awayPlayer: { id: "player-2", username: "prasen_legend", fullName: "Prasen Jit Sarker", rating: 950, avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80" },
    homeClub: { id: "club-1", name: "Dhaka Dominators Esports", shortName: "DDE", logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80" },
    awayClub: { id: "club-2", name: "Chittagong Cyber Kings", shortName: "CCK", logo: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=200&auto=format&fit=crop&q=80" },
    referee: { id: "ref-1", name: "Tanzid Hasan Joy", tier: "TIER_1", rating: 4.95 },
    result: { homeScore: 2, awayScore: 1, status: "PENDING" }
  },
  {
    id: "fix-live-2",
    tournamentId: "tourn-2",
    tournamentName: "Premier Super League S4",
    round: "Matchday 17",
    scheduledDate: "2026-09-19T19:00:00Z",
    venue: "Server BD-League-02",
    status: "LIVE",
    isOnStream: true,
    streamPlatform: "Twitch",
    streamUrl: "https://twitch.tv/efcob_official",
    homePlayer: { id: "player-4", username: "shakib_tactician", fullName: "Shakib Al Hasan", rating: 920, avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80" },
    awayPlayer: { id: "player-5", username: "easin_pro", fullName: "Easin Arafat", rating: 915, avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80" },
    homeClub: { id: "club-3", name: "Sylhet Strikers Esports", shortName: "SSE", logo: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=200&auto=format&fit=crop&q=80" },
    awayClub: { id: "club-4", name: "Rajshahi Royal FC", shortName: "RRF", logo: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=200&auto=format&fit=crop&q=80" },
    referee: { id: "ref-2", name: "Kamrul Islam Rabbi", tier: "TIER_1", rating: 4.90 },
    result: { homeScore: 0, awayScore: 0, status: "PENDING" }
  },
  // Upcoming Matches
  {
    id: "fix-up-1",
    tournamentId: "tourn-1",
    tournamentName: "National Championship 2026",
    round: "Semi Final 2",
    scheduledDate: "2026-09-20T19:30:00Z",
    venue: "Server BD-Championship-01",
    status: "SCHEDULED",
    isOnStream: true,
    streamPlatform: "YouTube",
    streamUrl: "https://youtube.com/live/efcob_sf2",
    homePlayer: { id: "player-3", username: "tanvir_efootball", fullName: "Tanvir Ahmed Chowdhury", rating: 935, avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80" },
    awayPlayer: { id: "player-6", username: "fahim_finisher", fullName: "Fahim Shahriar", rating: 895, avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80" },
    homeClub: { id: "club-1", name: "Dhaka Dominators Esports", shortName: "DDE", logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80" },
    awayClub: { id: "club-2", name: "Chittagong Cyber Kings", shortName: "CCK", logo: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=200&auto=format&fit=crop&q=80" },
    referee: { id: "ref-1", name: "Tanzid Hasan Joy", tier: "TIER_1", rating: 4.95 }
  },
  {
    id: "fix-up-2",
    tournamentId: "tourn-2",
    tournamentName: "Premier Super League S4",
    round: "Matchday 18",
    scheduledDate: "2026-09-21T18:00:00Z",
    venue: "Server BD-League-01",
    status: "SCHEDULED",
    isOnStream: false,
    homePlayer: { id: "player-7", username: "rakib_maestro", fullName: "Rakibul Islam", rating: 885, avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80" },
    awayPlayer: { id: "player-9", username: "sabbir_dribbler", fullName: "Sabbir Hossain", rating: 870, avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80" },
    homeClub: { id: "club-3", name: "Sylhet Strikers Esports", shortName: "SSE", logo: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=200&auto=format&fit=crop&q=80" },
    awayClub: { id: "club-5", name: "Barisal Blasters", shortName: "BBL", logo: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=200&auto=format&fit=crop&q=80" },
    referee: { id: "ref-3", name: "Shamim Hossain Patwary", tier: "TIER_2", rating: 4.82 }
  },
  {
    id: "fix-up-3",
    tournamentId: "tourn-2",
    tournamentName: "Premier Super League S4",
    round: "Matchday 18",
    scheduledDate: "2026-09-21T20:00:00Z",
    venue: "Server BD-League-02",
    status: "SCHEDULED",
    isOnStream: true,
    streamPlatform: "Facebook",
    streamUrl: "https://facebook.com/efcob/live",
    homePlayer: { id: "player-11", username: "mustafiz_speed", fullName: "Mustafizur Rahman", rating: 855, avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80" },
    awayPlayer: { id: "player-12", username: "shanto_wizard", fullName: "Najmul Hossain Shanto", rating: 850, avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80" },
    homeClub: { id: "club-4", name: "Rajshahi Royal FC", shortName: "RRF", logo: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=200&auto=format&fit=crop&q=80" },
    awayClub: { id: "club-6", name: "Khulna Knights Esports", shortName: "KKE", logo: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80" },
    referee: { id: "ref-4", name: "Mehedi Hasan Rana", tier: "TIER_2", rating: 4.75 }
  },
  // Completed Matches
  {
    id: "fix-fin-1",
    tournamentId: "tourn-1",
    tournamentName: "National Championship 2026",
    round: "Quarter Final 1",
    scheduledDate: "2026-09-17T18:00:00Z",
    venue: "Server BD-Championship-01",
    status: "FINISHED",
    isOnStream: true,
    streamPlatform: "YouTube",
    streamUrl: "https://youtube.com/watch?v=vod_qf1",
    homePlayer: { id: "player-1", username: "mahim_striker", fullName: "Mahim Haider", rating: 965, avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80" },
    awayPlayer: { id: "player-5", username: "easin_pro", fullName: "Easin Arafat", rating: 915, avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80" },
    homeClub: { id: "club-1", name: "Dhaka Dominators Esports", shortName: "DDE", logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80" },
    awayClub: { id: "club-4", name: "Rajshahi Royal FC", shortName: "RRF", logo: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=200&auto=format&fit=crop&q=80" },
    referee: { id: "ref-1", name: "Tanzid Hasan Joy", tier: "TIER_1", rating: 4.95 },
    result: {
      homeScore: 3,
      awayScore: 1,
      motmPlayerName: "Mahim Haider",
      motmPlayerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
      motmReason: "Scored a sensational hat-trick in 65 minutes with 5 on-target shots.",
      status: "APPROVED"
    }
  },
  {
    id: "fix-fin-2",
    tournamentId: "tourn-1",
    tournamentName: "National Championship 2026",
    round: "Quarter Final 2",
    scheduledDate: "2026-09-17T20:00:00Z",
    venue: "Server BD-Championship-02",
    status: "FINISHED",
    isOnStream: true,
    streamPlatform: "YouTube",
    streamUrl: "https://youtube.com/watch?v=vod_qf2",
    homePlayer: { id: "player-2", username: "prasen_legend", fullName: "Prasen Jit Sarker", rating: 950, avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80" },
    awayPlayer: { id: "player-4", username: "shakib_tactician", fullName: "Shakib Al Hasan", rating: 920, avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80" },
    homeClub: { id: "club-2", name: "Chittagong Cyber Kings", shortName: "CCK", logo: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=200&auto=format&fit=crop&q=80" },
    awayClub: { id: "club-3", name: "Sylhet Strikers Esports", shortName: "SSE", logo: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=200&auto=format&fit=crop&q=80" },
    referee: { id: "ref-2", name: "Kamrul Islam Rabbi", tier: "TIER_1", rating: 4.90 },
    result: {
      homeScore: 2,
      awayScore: 0,
      motmPlayerName: "Prasen Jit Sarker",
      motmPlayerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
      motmReason: "Masterminded two exquisite through balls and controlled 64% ball possession.",
      status: "APPROVED"
    }
  },
  {
    id: "fix-fin-3",
    tournamentId: "tourn-2",
    tournamentName: "Premier Super League S4",
    round: "Matchday 16",
    scheduledDate: "2026-09-15T19:00:00Z",
    venue: "Server BD-League-01",
    status: "FINISHED",
    isOnStream: false,
    homePlayer: { id: "player-1", username: "mahim_striker", fullName: "Mahim Haider", rating: 965, avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80" },
    awayPlayer: { id: "player-7", username: "rakib_maestro", fullName: "Rakibul Islam", rating: 885, avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80" },
    homeClub: { id: "club-1", name: "Dhaka Dominators Esports", shortName: "DDE", logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=200&auto=format&fit=crop&q=80" },
    awayClub: { id: "club-3", name: "Sylhet Strikers Esports", shortName: "SSE", logo: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=200&auto=format&fit=crop&q=80" },
    referee: { id: "ref-1", name: "Tanzid Hasan Joy", tier: "TIER_1", rating: 4.95 },
    result: {
      homeScore: 3,
      awayScore: 2,
      motmPlayerName: "Mahim Haider",
      motmPlayerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
      motmReason: "90th-minute winning curler to seal thrilling 3 points.",
      status: "APPROVED"
    }
  }
];

export const INITIAL_ACTIVITY_EVENTS = [
  {
    id: "act-1",
    type: "MATCH_WIN",
    category: "Matches",
    title: "Mahim Haider secured a 3-1 victory in the Championship Quarter Final",
    description: "Dhaka Dominators striker dispatched 3 clinical goals to progress to the Semi-Finals.",
    createdAt: "2026-09-18T19:45:00Z",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    targetUrl: "/matches/fix-fin-1"
  },
  {
    id: "act-2",
    type: "MOTM_AWARD",
    category: "Awards",
    title: "Prasen Jit Sarker awarded Man of the Match",
    description: "Official referee Tanzid Joy confirmed MOTM honors with 2 assists and 64% ball possession.",
    createdAt: "2026-09-18T18:10:00Z",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    targetUrl: "/matches/fix-fin-2"
  },
  {
    id: "act-3",
    type: "TRANSFER",
    category: "Transfers",
    title: "Dhaka Dominators Esports finalized signing of Arifuzzaman Khan",
    description: "Record $115M valuation transfer confirmed with a 2-year contract.",
    createdAt: "2026-09-17T14:30:00Z",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    targetUrl: "/transfer-market"
  },
  {
    id: "act-4",
    type: "GOALS_SCORED",
    category: "Players",
    title: "Tanvir Ahmed surpassed 40 career goals in eFCOB competitions",
    description: "Sylhet Strikers shadow striker joins the elite 40+ goal club.",
    createdAt: "2026-09-16T21:00:00Z",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    targetUrl: "/players/tanvir_efootball"
  },
  {
    id: "act-5",
    type: "TOURNAMENT_START",
    category: "Tournaments",
    title: "Registration opened for Dhaka Esports Champions Cup 2026",
    description: "16 slots open for competitive grassroots clubs with 50,000 BDT prize pool.",
    createdAt: "2026-09-15T10:00:00Z",
    avatar: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=200&auto=format&fit=crop&q=80",
    targetUrl: "/tournaments/dhaka-champions-cup-2026"
  }
];

export const INITIAL_NEWS_ARTICLES = [
  {
    id: "news-1",
    title: "eFCOB National Championship 2026: Semi-Finalists Locked In",
    slug: "national-championship-2026-semi-finals",
    excerpt: "The four most decorated players in Bangladesh will clash on Saturday in what promises to be the highest level of mobile esports ever broadcast.",
    content: "The Quarter Finals of the Bangladesh National eFootball Championship 2026 delivered heart-stopping drama as Mahim Haider, Prasen Jit Sarker, Tanvir Ahmed, and Fahim Shahriar booked their spots in the final four. With over 25,000 peak concurrent viewers on the live stream, the tournament sets new benchmarks for competitive digital football.",
    featuredImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80",
    author: "NECOB Press Office",
    category: "Tournament",
    tags: ["Championship", "Esports", "Mobile", "SemiFinals"],
    publishedDate: "2026-09-18T10:00:00Z",
    views: 4820,
    isFeatured: true
  },
  {
    id: "news-2",
    title: "Official Transfer Window S4 Opens with Historic $180M Record Valuations",
    slug: "transfer-window-s4-record-valuations",
    excerpt: "Top 10 clubs begin contract extensions and player bids as the competitive ecosystem expands across national divisions.",
    content: "The Mid-Season Transfer Window for 2026 is officially open. Club managers from Dhaka Dominators, CCK, and Sylhet Strikers have placed high-priority bids on emerging wingers and tier-1 defensive anchors.",
    featuredImage: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1200&auto=format&fit=crop&q=80",
    author: "Transfer Market Bureau",
    category: "Announcement",
    tags: ["Transfers", "Contracts", "Clubs"],
    publishedDate: "2026-09-16T15:00:00Z",
    views: 3150,
    isFeatured: false
  },
  {
    id: "news-3",
    title: "New Match Official Certification Program & Fair Play Charter",
    slug: "referee-certification-program-2026",
    excerpt: "NECOB introduces Tier 1-3 referee accreditations to guarantee 100% dispute resolution integrity across all tier competitions.",
    content: "Under the leadership of Senior Head Referee Tanzid Hasan Joy, all official fixtures will now require dual referee sign-off, live screenshot verification, and automated Elo dispute auditing.",
    featuredImage: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80",
    author: "Governance Committee",
    category: "Community",
    tags: ["Referees", "Rules", "FairPlay"],
    publishedDate: "2026-09-14T12:00:00Z",
    views: 2280,
    isFeatured: false
  }
];

export const INITIAL_EVENTS = [
  {
    id: "event-1",
    name: "eFCOB Grand Finals 2026 — Live LAN Arena",
    slug: "grand-finals-2026-lan",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80",
    description: "The grandest esports stage in Bangladesh! Witness the crowning of the 2026 Champion live at the Bashundhara Convention City.",
    venue: "ICCB Hall 4, Dhaka",
    eventDate: "2026-10-25T14:00:00Z",
    capacity: 1500,
    registeredCount: 890,
    status: "ACTIVE"
  },
  {
    id: "event-2",
    name: "Chittagong eFootball Community Meetup & 1v1 Gauntlet",
    slug: "chittagong-meetup-2026",
    banner: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80",
    description: "A community celebration featuring speed challenges, tactics workshops with pro players, and prize giveaways.",
    venue: "GEC Convention Centre, Chittagong",
    eventDate: "2026-11-08T15:00:00Z",
    capacity: 400,
    registeredCount: 260,
    status: "ACTIVE"
  }
];

export const INITIAL_LEADERSHIP = [
  {
    id: "lead-1",
    name: "Khandaker Faisal",
    role: "President & Founder",
    category: "Founders",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    period: "2023 - Present",
    bio: "Pioneered structured competitive eFootball in Bangladesh. Built the national league architecture.",
    facebook: "https://facebook.com"
  },
  {
    id: "lead-2",
    name: "Tanzid Hasan Joy",
    role: "Head of Match Officials & Disciplinary",
    category: "Core Team",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    period: "2023 - Present",
    bio: "Chief adjudicator ensuring tournament rule enforcement, referee training, and fair-play ethics.",
    facebook: "https://facebook.com"
  },
  {
    id: "lead-3",
    name: "Syed Shakil Ahmed",
    role: "Director of Tournament Operations",
    category: "Core Team",
    photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80",
    period: "2024 - Present",
    bio: "Broadcast producer and competition manager orchestrating national double-elimination brackets.",
    facebook: "https://facebook.com"
  },
  {
    id: "lead-4",
    name: "Sabbir Hossain",
    role: "Community Relations & Partner Director",
    category: "Core Team",
    photo: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80",
    period: "2024 - Present",
    bio: "Expands university esports leagues and gaming community partnerships across 8 administrative divisions.",
    facebook: "https://facebook.com"
  }
];

export const INITIAL_PARTNERS = [
  {
    id: "part-1",
    name: "BRAC University Esports Club",
    category: "University",
    logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=200&auto=format&fit=crop&q=80",
    website: "https://bracu.ac.bd",
    description: "Official collegiate partner organizing inter-university esports qualifiers."
  },
  {
    id: "part-2",
    name: "North South University Gaming Guild",
    category: "University",
    logo: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=200&auto=format&fit=crop&q=80",
    website: "https://northsouth.edu",
    description: "Collegiate esports community with over 1,200 active members."
  },
  {
    id: "part-3",
    name: "Bangladesh Cyber Athletes Guild",
    category: "Esports Club",
    logo: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=200&auto=format&fit=crop&q=80",
    website: "https://facebook.com",
    description: "Premier grassroots community talent incubator."
  }
];

export const INITIAL_SPONSORS = [
  {
    id: "spon-1",
    name: "Apex Gaming Hardware",
    logo: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=200&auto=format&fit=crop&q=80",
    website: "https://apex.gg",
    placement: "Homepage",
    priority: 1
  },
  {
    id: "spon-2",
    name: "Volt Energy Drinks",
    logo: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=200&auto=format&fit=crop&q=80",
    website: "https://voltenergy.com",
    placement: "Tournament",
    priority: 2
  },
  {
    id: "spon-3",
    name: "SpeedNet Fiber Broadband",
    logo: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=200&auto=format&fit=crop&q=80",
    website: "https://speednet.bd",
    placement: "MatchCentre",
    priority: 3
  }
];
