import { Role } from "@/types";

export const PERMISSIONS = {
  // Players
  PLAYERS_READ: "players:read",
  PLAYERS_CREATE: "players:create",
  PLAYERS_UPDATE_OWN: "players:update_own",
  PLAYERS_UPDATE_ANY: "players:update_any",
  PLAYERS_DELETE: "players:delete",
  PLAYERS_SUSPEND: "players:suspend",
  PLAYERS_VERIFY: "players:verify",

  // Clubs
  CLUBS_READ: "clubs:read",
  CLUBS_CREATE: "clubs:create",
  CLUBS_MANAGE_OWN: "clubs:manage_own",
  CLUBS_MANAGE_ANY: "clubs:manage_any",
  CLUBS_APPROVE: "clubs:approve",
  CLUBS_SUSPEND: "clubs:suspend",

  // Tournaments
  TOURNAMENTS_READ: "tournaments:read",
  TOURNAMENTS_CREATE: "tournaments:create",
  TOURNAMENTS_MANAGE: "tournaments:manage",
  TOURNAMENTS_BRACKET_GENERATE: "tournaments:bracket_generate",

  // Fixtures & Matches
  FIXTURES_READ: "fixtures:read",
  FIXTURES_CREATE: "fixtures:create",
  FIXTURES_UPDATE: "fixtures:update",
  MATCHES_SUBMIT_RESULT: "matches:submit_result",
  MATCHES_APPROVE_RESULT: "matches:approve_result",
  MATCHES_DISPUTE: "matches:dispute",

  // Referees
  REFEREES_ASSIGN: "referees:assign",
  REFEREES_REPORT: "referees:report",
  REFEREES_MANAGE: "referees:manage",

  // Transfers
  TRANSFERS_REQUEST: "transfers:request",
  TRANSFERS_APPROVE: "transfers:approve",
  TRANSFERS_MODERATE: "transfers:moderate",

  // Admin & Disciplinary
  DISCIPLINARY_MANAGE: "disciplinary:manage",
  CMS_MANAGE: "cms:manage",
  AUDIT_READ: "audit:read",
  SUPER_ADMIN_ALL: "super_admin:all",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.PLAYERS_READ,
    PERMISSIONS.PLAYERS_CREATE,
    PERMISSIONS.PLAYERS_UPDATE_ANY,
    PERMISSIONS.PLAYERS_DELETE,
    PERMISSIONS.PLAYERS_SUSPEND,
    PERMISSIONS.PLAYERS_VERIFY,
    PERMISSIONS.CLUBS_READ,
    PERMISSIONS.CLUBS_CREATE,
    PERMISSIONS.CLUBS_MANAGE_ANY,
    PERMISSIONS.CLUBS_APPROVE,
    PERMISSIONS.CLUBS_SUSPEND,
    PERMISSIONS.TOURNAMENTS_READ,
    PERMISSIONS.TOURNAMENTS_CREATE,
    PERMISSIONS.TOURNAMENTS_MANAGE,
    PERMISSIONS.TOURNAMENTS_BRACKET_GENERATE,
    PERMISSIONS.FIXTURES_READ,
    PERMISSIONS.FIXTURES_CREATE,
    PERMISSIONS.FIXTURES_UPDATE,
    PERMISSIONS.MATCHES_SUBMIT_RESULT,
    PERMISSIONS.MATCHES_APPROVE_RESULT,
    PERMISSIONS.MATCHES_DISPUTE,
    PERMISSIONS.REFEREES_ASSIGN,
    PERMISSIONS.REFEREES_MANAGE,
    PERMISSIONS.TRANSFERS_MODERATE,
    PERMISSIONS.DISCIPLINARY_MANAGE,
    PERMISSIONS.CMS_MANAGE,
    PERMISSIONS.AUDIT_READ,
  ],
  MODERATOR: [
    PERMISSIONS.PLAYERS_READ,
    PERMISSIONS.PLAYERS_VERIFY,
    PERMISSIONS.CLUBS_READ,
    PERMISSIONS.TOURNAMENTS_READ,
    PERMISSIONS.FIXTURES_READ,
    PERMISSIONS.MATCHES_APPROVE_RESULT,
    PERMISSIONS.MATCHES_DISPUTE,
    PERMISSIONS.DISCIPLINARY_MANAGE,
  ],
  TOURNAMENT_OFFICIAL: [
    PERMISSIONS.PLAYERS_READ,
    PERMISSIONS.CLUBS_READ,
    PERMISSIONS.TOURNAMENTS_READ,
    PERMISSIONS.TOURNAMENTS_MANAGE,
    PERMISSIONS.FIXTURES_READ,
    PERMISSIONS.FIXTURES_CREATE,
    PERMISSIONS.FIXTURES_UPDATE,
    PERMISSIONS.MATCHES_APPROVE_RESULT,
    PERMISSIONS.REFEREES_ASSIGN,
  ],
  SENIOR_REFEREE: [
    PERMISSIONS.PLAYERS_READ,
    PERMISSIONS.CLUBS_READ,
    PERMISSIONS.FIXTURES_READ,
    PERMISSIONS.REFEREES_REPORT,
    PERMISSIONS.MATCHES_SUBMIT_RESULT,
    PERMISSIONS.MATCHES_APPROVE_RESULT,
  ],
  REFEREE: [
    PERMISSIONS.PLAYERS_READ,
    PERMISSIONS.CLUBS_READ,
    PERMISSIONS.FIXTURES_READ,
    PERMISSIONS.REFEREES_REPORT,
    PERMISSIONS.MATCHES_SUBMIT_RESULT,
  ],
  CLUB_MANAGER: [
    PERMISSIONS.PLAYERS_READ,
    PERMISSIONS.CLUBS_READ,
    PERMISSIONS.CLUBS_MANAGE_OWN,
    PERMISSIONS.FIXTURES_READ,
    PERMISSIONS.TOURNAMENTS_READ,
    PERMISSIONS.TRANSFERS_REQUEST,
    PERMISSIONS.TRANSFERS_APPROVE,
    PERMISSIONS.MATCHES_SUBMIT_RESULT,
    PERMISSIONS.MATCHES_DISPUTE,
  ],
  PLAYER: [
    PERMISSIONS.PLAYERS_READ,
    PERMISSIONS.PLAYERS_UPDATE_OWN,
    PERMISSIONS.CLUBS_READ,
    PERMISSIONS.TOURNAMENTS_READ,
    PERMISSIONS.FIXTURES_READ,
    PERMISSIONS.MATCHES_SUBMIT_RESULT,
    PERMISSIONS.MATCHES_DISPUTE,
  ],
};

export function hasPermission(role: Role, permission: Permission): boolean {
  if (role === "SUPER_ADMIN") return true;
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}
